name: SAST Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sast_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Semgrep
        run: |
          python -m pip install --upgrade pip
          pip install semgrep

      - name: Run SAST Scan
        run: semgrep --config=auto --json . > sast-report.json

      - name: Display SAST Report
        run: cat sast-report.json

      - name: Upload SAST Report Artifact
        uses: actions/upload-artifact@v3
        with:
          name: sast-report
          path: sast-report.json
